routes/web.php
Route::get('/', function () {
    return redirect(route('login'));
});

Route::patch('firstConnect/{id}', 'Auth\LoginController@firstConnect')->name('firstConnect');
Route::post('authenticate', 'Auth\LoginController@authenticate')->name('authenticate');

Auth::routes(['verify' => true]);
Auth::routes(['register' => false]);
Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
Route::get('/admin', 'HomeController@index')->name('admin')->middleware('verified');
Route::middleware('auth')->group(function () {
    Route::group(['middleware' => ['role:ADMIN']], function () {
    });

    Route::group(['middleware' => ['role:CSS']], function () {
    });

    Route::group(['middleware' => ['role:CSR']], function () {
    });

    Route::group(['middleware' => ['role:SUPERADMIN']], function () {
    });

    // Routes for Admin Role
    Route::group(['middleware' => ['permission:GERER_COMPTE']], function () {
        Route::resource('users', 'UsersController');
        Route::patch('/lockAndUnlockAccount/{id}', 'Auth\AccountController@lockAndUnlock')->name('lockAndUnlockAccount');
        Route::get('reinitialiserMotDePasse/{id}', 'Auth\AccountController@reinitialiserMotDePasse')->name('reinitialiserMotDePasse');
        Route::get('users/{user_id}/editCompte', 'UsersController@editUser')->name('users.compte.edit');
        Route::get('historique/{id}', 'ActivityLogController@getActivitiesLog')->name('historique.index');
        Route::post('activityLogSearch', 'ActivityLogController@activityLogSearch')->name('activityLogSearch');
    });
    Route::group(['middleware' => ['permission:GERER_PROFIL']], function () {
        Route::resource('roles', 'RolesController');
        Route::resource('permissions', 'PermissionsController');
    });

    Route::get('/formUserPassword', 'Auth\AccountController@formPassword')->name('formMyPassword');
    Route::patch('/changeUserPassword', 'Auth\AccountController@changePassword')->name('changeMyPassword');
    Route::patch('/update_account', 'UsersController@update_account')->name('update_account');
    Route::get('logout', 'Auth\LoginController@logout');

    Route::group(['middleware' => ['permission:GERER_STRUCTURE']], function () {
        Route::resource('structures', 'StructuresController');
        Route::get('deleteStructure/{id_structure}', 'StructuresController@deleteStructure')->name('deleteStructure');
        Route::get('structuresSearch', 'StructuresController@structuresSearch')->name('structuresSearch');

    });
    Route::group(['middleware' => ['permission:GERER_CATEGORIE_STRUCTURE']], function () {
        Route::resource('categories', 'CategoriesController');
        Route::get('deleteCategorie/{id_categorie}', 'CategoriesController@deleteCategorie')->name('deleteCategorie');
     });

    Route::get('users/{user_id}/showCompte', 'UsersController@showUser')->name('users.compte.show');
    Route::get('getAgentsStructure/{id_structure}', 'UsersController@getAgentsStructure')->name('getAgentsStructure');
    Route::get('getPageAgentSuivi/{id_structure}', 'UsersController@getPageAgentSuivi')->name('getPageAgentSuivi');
    Route::get('getPageParticipants/{id_session}', 'SessionController@getPageParticipants')->name('getPageParticipants');

    Route::resource('acteurs', 'ActeurController');
    Route::get('getPageActeursInstance/{id_instance}', 'ActeurController@getPageActeursInstance')->name('getPageActeursInstance');
    Route::post('saveActeur', 'ActeurController@saveActeur')->name('saveActeur');
    Route::get('getActeur/{id_acteur}', 'ActeurController@getActeur')->name('getActeur');
    Route::get('getAllActeurs', 'ActeurController@getAllActeurs')->name('getAllActeurs');
    Route::get('deleteActeur/{id_acteur}', 'ActeurController@deleteActeur')->name('deleteActeur');
    Route::get('setCss/{id_acteur}', 'ActeurController@setCss')->name('setCss');
    Route::get('setCsr/{id_acteur}', 'ActeurController@setCsr')->name('setCsr');

    Route::resource('instances', 'InstanceController');
    Route::post('saveInstance', 'InstanceController@saveInstance')->name('saveInstance');
    Route::get('getInstance/{id_instance}', 'InstanceController@getInstance')->name('getInstance');
    Route::get('getAllInstances', 'InstanceController@getAllInstances')->name('getAllInstances');
    Route::get('getAllInstancesCSS', 'InstanceController@getAllInstancesCSS')->name('getAllInstancesCSS');
    Route::get('deleteInstance/{id_instance}', 'InstanceController@deleteInstance')->name('deleteInstance');
    Route::get('supprimerProfil/{id_role}', 'RolesController@supprimerProfil')->name('supprimerProfil');

    Route::resource('sessions', 'SessionController');
    Route::post('saveSession', 'SessionController@saveSession')->name('saveSession');
    Route::post('changeStatus/{id_session}/{value}', 'SessionController@changeStatus')->name('changeStatus');
    Route::get('sessionsSearch', 'SessionController@sessionsSearch')->name('sessionsSearch');
    Route::get('structuresWhereRecoNotPlan/{ses_id}', 'SessionController@structuresWhereRecoNotPlan')->name('structuresWhereRecoNotPlan');
    Route::post('joindreListParticipant', 'SessionController@joindreListParticipant')->name('joindreListParticipant');
    Route::get('getSession/{id_session}', 'SessionController@getSession')->name('getSession');
    Route::get('getAllSessions', 'SessionController@getAllSessions')->name('getAllSessions');
    Route::get('getAllSessionsEnFormulation', 'SessionController@getAllSessionsEnFormulation')->name('getAllSessionsEnFormulation');
    Route::get('deleteSession/{id_session}', 'SessionController@deleteSession')->name('deleteSession');
    Route::get('getRecosAreconduire/{ses_id_precedant}', 'SessionController@getRecosAreconduire')->name('getRecosAreconduire');
    Route::post('reconduireRecos', 'SessionController@reconduireRecos')->name('reconduireRecos');
    //    Route::get('reconduireRecos/{ses_id}/{ses_id_precedant}', 'SessionController@reconduireRecos')->name('reconduireRecos');

    
    Route::get('usersSearch', 'UsersController@usersSearch')->name('usersSearch');
    Route::get('deleteAgent/{id_agent}', 'AgentsController@deleteAgent')->name('deleteAgent');
    Route::get('getStructure/{id_structure}', 'StructuresController@getStructure')->name('getStructure');
    Route::get('getCategorie/{id_categorie}', 'CategoriesController@getCategorie')->name('getCategorie');
    Route::get('getAgent/{id_agent}', 'AgentsController@getAgent')->name('getAgent');
    Route::resource('templatemsgs', 'TemplatemsgsController');

    //routes for template
    Route::post('templatemsgs/save', 'TemplatemsgsController@save')->name('saveTemplate');
    Route::post('templatemsgs/updating/{id}', 'TemplatemsgsController@updating')->name('UpdatingTemplate');
    Route::get('templatemsgs/delete/{id}', 'TemplatemsgsController@delete')->name('deleteTemplate');
    Route::get('params/structure', 'TemplatemsgsController@listeStructure')->name('paramsStructure');
    Route::get('templatemsgs/detail/{id}', 'TemplatemsgsController@detailTemplate')->name('detailTemplate');
    Route::get('getTemplate/{id}', 'TemplatemsgsController@getTemplate')->name('getTemplate');
    //fin routes for template

    //debut route for alerts
    Route::get('instance/getSession/{id}', 'AlertesController@getSession')->name('getSession');
    Route::get('getModele', 'AlertesController@getModele')->name('getModele');
    Route::post('alertes/save', 'AlertesController@save')->name('SaveSession');
    Route::get('deleteAlerte/{id}', 'AlertesController@delete')->name('deleteAlerte');
    Route::get('getAlerte/{id}', 'AlertesController@getAlerte')->name('getAlerte');
    Route::post('alerte/updating/{id}', 'AlertesController@updating')->name('UpdateAlerte');
    Route::get('ConsulterMessage/{id}', 'AlertesController@ConsulterMessage')->name('ConsulterMessage');
    Route::get('filtreAlerte', 'AlertesController@filtreAlerteMessage')->name('filtreAlerte');
    Route::get('sendAlerte/{id}', 'EnvoiAlertesController@sendAlerte')->name('sendAlerte');
    Route::get('resendAlerte/{id}', 'EnvoiAlertesController@resendAlerte')->name('resendAlerte');
    Route::get('alertSearch', 'AlertesController@alertSearch')->name('alertSearch');
    Route::get('alerte/boiteReception', 'AlertesController@alertInbox')->name('alertInbox');
    Route::get('alerte/boiteReception/detail/{id}', 'AlertesController@infoAlerte')->name('alertInfo');
    Route::get('getMsg/{id}', 'AlertesController@getMsg')->name('getMsg');
    Route::get('alerte/listMessage/{id}', 'AlertesController@listEnvoi')->name('listMessage');
    Route::get('alertMessageSearch/', 'AlertesController@alertMessageSearch')->name('alertMessageSearch');
    //fin route for alerts

    //routes for envoiealertes
    Route::get('sendAlerte/{id}', 'EnvoiAlertesController@sendAlerte')->name('sendAlerte');
    Route::get('ListeEmailNotSend', 'EnvoiAlertesController@ListeEmailNotSend')->name('ListeEmailNotSend');
    Route::get('alerting', 'EnvoiAlertesController@alerting')->name('notifr'); //route pour tester seulement
    //
    Route::resource('alertes', 'AlertesController');
    Route::get('getPageAlertesSession/{id_session}', 'AlertesController@getPageAlertesSession')->name('getPageAlertesSession');

    Route::resource('participants', 'ParticipantsController');
    Route::get('getPageParticipantsSession/{id_session}', 'ParticipantsController@getPageParticipantsSession')->name('getPageParticipantsSession');

    Route::resource('recommandations', 'RecommandationsController');
    Route::get('getPageRecosBySession/{id_session}', 'RecommandationsController@getPageRecosBySession')->name('getPageRecosBySession');
    Route::get('getPageSaisieRecos', 'RecommandationsController@getPageSaisieRecos')->name('getPageSaisieRecos');
    Route::get('getPagePlaningRecos', 'RecommandationsController@getPagePlaningRecos', 'RecommandationsController@getPagePlaningRecos')->name('getPagePlaningRecos');

app/Models/Instance.php
<?php

namespace App\Models;

use Eloquent as Model;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * Class Instance
 * @package App\Models
 * @version February 17, 2020, 11:39 pm UTC
 *
 * @property string ins_sigle
 * @property string ins_nom_complet
 * @property integer ins_nbr_session
 * @property string ins_periodicite
 * @property string ins_description
 * @property string ins_ref_arrete
 * @property string created_by
 * @property string updated_by
 */
class Instance extends Model
{
    use LogsActivity; 

    public $table = 'instances';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';



    protected $primaryKey = 'ins_id';

    public $fillable = [
//        'bud_id',
        'ins_sigle',
        'ins_nom_complet',
        'ins_nbr_session',
        'ins_periodicite',
        'ins_description',
        'ins_ref_arrete',
        'created_by',
        'updated_by'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'ins_id' => 'integer',
//        'bud_id' => 'integer',
        'ins_sigle' => 'string',
        'ins_nom_complet' => 'string',
        'ins_nbr_session' => 'integer',
        'ins_periodicite' => 'string',
        'ins_description' => 'string',
        'ins_ref_arrete' => 'string',
        'created_by' => 'string',
        'updated_by' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
//        'bud_id' => 'required',
        'ins_sigle' => 'required',
        'ins_nom_complet' => 'required',
        'ins_nbr_session' => 'required',
        'ins_periodicite' => 'required',
        'created_by' => 'required',
        'created_at' => 'required'
    ];

    protected static $logName = 'Instance';
    public function getDescriptionForEvent(string $eventName): string
    {
        if ($eventName == 'created') {
            return "Création";
        } elseif ($eventName == 'updated') {
            return "Modification";
        } elseif ($eventName == 'deleted') {
            return "Suppression";
        }
    } 
}

resources/views/backend/instances/create.blade.php
@extends('layouts.template')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('instances.index') !!}">Instance</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                {{-- @include('coreui-templates::common.errors') --}}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Instance</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'instances.store']) !!}

                                   @include('backend.instances.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/backend/instances/edit.blade.php
@extends('layouts.template')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('instances.index') !!}">Instance</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             {{-- @include('coreui-templates::common.errors') --}}
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Instance</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($instance, ['route' => ['instances.update', $instance->ins_id], 'method' => 'patch']) !!}

                              @include('backend.instances.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/backend/instances/fields.blade.php
<!-- Ins Sigle Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ins_sigle', 'Ins Sigle:') !!}
    {!! Form::text('ins_sigle', null, ['class' => 'form-control']) !!}
</div>

<!-- Ins Nom Complet Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ins_nom_complet', 'Ins Nom Complet:') !!}
    {!! Form::text('ins_nom_complet', null, ['class' => 'form-control']) !!}
</div>

<!-- Ins Nbr Session Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ins_nbr_session', 'Ins Nbr Session:') !!}
    {!! Form::number('ins_nbr_session', null, ['class' => 'form-control']) !!}
</div>

<!-- Ins Periodicite Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ins_periodicite', 'Ins Periodicite:') !!}
    {!! Form::text('ins_periodicite', null, ['class' => 'form-control']) !!}
</div>

<!-- Ins Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('ins_description', 'Ins Description:') !!}
    {!! Form::textarea('ins_description', null, ['class' => 'form-control']) !!}
</div>

<!-- Created By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('created_by', 'Created By:') !!}
    {!! Form::text('created_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Updated By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('updated_by', 'Updated By:') !!}
    {!! Form::text('updated_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('instances.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/backend/instances/index.blade.php
@extends('layouts.template')
@section('title')
    Instances
    @parent
@stop

@section('header_styles')
    <link rel="stylesheet" type="text/css" href="{{ url('backend/css/sweetalert2.min.css') }}"/>
@stop

@section('content')
    <div class="container-fluid">
        <div class="card mb-2">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0);">Paramètre</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Gestion des instances</li>
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header widget-content">
                        <div class="widget-content-wrapper">
                            <div class="widget-content-left">
                                <div class="card-title">Liste des instances</div>
                            </div>
                            <div class="widget-content-right">
                                {{--<button type="button" class="btn btn-sm btn-primary"
                                        onclick="window.location.href='{{ url('programmeBudgetaires') }}'">
                                    <i class="fa fa-wrench fa-lg"></i>&nbsp;&nbsp;G&eacute;rer programme budg&eacute;taire
                                </button>--}}
                                <button type="button" class="btn btn-sm btn-primary"
                                        onclick="openModalAddInstance(null)"
                                        data-toggle="modal" data-target="#modalAddInstance">
                                    <i class="fa fa-plus-square fa-lg"></i>&nbsp;&nbsp;Nouvelle instance
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row my-2">
                    <div class="col-lg-12 col-xl-12 mb-3">
                        <div class="card">
                            <div class="card-body">
                                @include('backend.instances.table')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript" src="{{ url('backend/js/sweetalert2.all.min.js') }}"></script>
    <script src="{{ url('backend/js/date.format.js') }}" type="text/javascript"></script>
    <script>
        function openModalAddInstance(id) {
            $('.selectSearch').select2({
                width: '100%',
                dropdownParent: $("#formAddInstance"),
                placeholder: "Choisir...",
                allowClear: true
            });
            $('#formAddInstance').attr('action', 'saveInstance');
            if (id == null) {
                $('.modal-title').text('Ajout d\'une nouvelle instance');
                $('#btnSave').text('Enregistrer');
                $('#ins_id').val(null);
                $('#ins_sigle').val(null);
                $('#ins_nom_complet').val(null);
                $('#ins_nbr_session').val(null);
                $('#ins_periodicite').val('null');
                $('#ins_description').val(null);
                $('#ins_ref_arrete').val(null);
            }
            else {
                $.ajax({
                    url: "{{ url("/getInstance") }}/" + id,
                    type: "GET",
                    dataType: "JSON",
                    success: function (data) {
                        console.log(data);
                        $('.modal-title').text('Modification d\'une instance');
                        $('#btnSave').text('Modifier');
                        if (data.ins_id != null && data.ins_id != undefined) {
                            $('#ins_id').val(id);
                            $('#bud_id').val(data.bud_id);
                            $('#ins_sigle').val(data.ins_sigle);
                            $('#ins_nom_complet').val(data.ins_nom_complet);
                            $('#ins_nbr_session').val(data.ins_nbr_session);
                            $('#ins_periodicite').val(data.ins_periodicite);
                            $('#ins_description').val(data.ins_description);
                            $('#ins_ref_arrete').val(data.ins_ref_arrete);
                        }
                    },
                    error: function () {
                        alert("Erreur rencontrer lors de la recuperation des donnees!");
                    }
                });
            }
        }

        function openModalDetail(id) {
            $.ajax({
                url: "{{url('/getInstance')}}/" + id,
                type: "get",
                success: function (data) {
                    var options = {weekday: "long", year: "numeric", month: "long", day: "numeric"};
                    var optionsWithTime = {year: "numeric", month: "long", day: "numeric", hour: "numeric", minute: "numeric", second: "numeric"};

                    if (data.ins_id != null && data.ins_id > 0) {
                        $('.modal-title').text("Détails de l'instance : " + data.ins_sigle);
                        $('#libSigle').text(data.ins_sigle);
                        $('#libNom').text(data.ins_nom_complet);
                        $('#libNbSession').text(data.ins_nbr_session);
                        $('#libPeriodicite').html('<span class="badge badge-info">' + data.ins_periodicite + '</span>');
                        $('#libArr').text(data.ins_ref_arrete);
                        $('#libPbg').text(data.bud_intitule);
                        $('#libDesc').text(data.ins_description);
                        if (data.created_at != null && data.created_at != '') {
                            // $('#libCreatedAt').text(dateFormat(data.created_at, "dd/mm/yyyy à HH:mm:ss"));
                            var dtCree = new Date(data.created_at);
                            var datCree = dtCree.toLocaleDateString("fr-FR", optionsWithTime);
                            $('#libCreatedAt').text(datCree);
                            $('#libCreatedBy').text(data.created_by);
                        }
                        if (data.updated_at != null && data.updated_at != '') {
                            // $('#libUpdatedAt').text(dateFormat(data.updated_at, "dd/mm/yyyy à HH:mm:ss"));
                            var dtMod = new Date(data.updated_at);
                            var datMod = dtMod.toLocaleDateString("fr-FR", optionsWithTime);
                            $('#libUpdatedAt').text(datMod);
                            $('#libUpdatedBy').text(data.updated_by);
                        }
                    }
                },
                error: function (data) {
                    swal({
                        title: 'Erreur',
                        text: "Une erreure est survenue lors de la récupération des données de l'instance!\nVeuillez reessayer!",
                        type: 'error',
                        button: "OK"
                    });
                }
            });
        }

        function deleteInstance(id, libelle) {
            swal({
                title: 'CONFIRMATION',
                text: "Etes vous sûr de vouloir supprimer définitivement l'instance : " + libelle + " ?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Oui, supprimer!',
                cancelButtonText: 'Non, annuler',
                reverseButtons: true,
                showLoaderOnConfirm: true,
                preConfirm: function () {
                    return new Promise(function (resolve) {
                        $.ajaxSetup({
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                            }
                        });
                        $.ajax({
                            url: "{{url('/deleteInstance')}}/" + id,
                            type: "get",
                            data: {ins_id: id, '_token': '{{csrf_token()}}'},
                            success: function (data) {
                                if (data == 0) {
                                    swal({
                                        title: 'Attention',
                                        text: "Impossible de supprimer cette instance, elle est rattachée à certaines données !",
                                        type: 'info',
                                        button: "OK"
                                    });
                                } else {
                                    swal({
                                        title: "Succes!",
                                        text: "Suppression de l'instance effectuée avec succès!",
                                        type: "success",
                                        button: "OK"
                                    }).then(function () {
                                        location.reload();
                                    });
                                }
                            },
                            error: function (data) {
                                swal({
                                    title: 'Erreur',
                                    text: "Une erreure est survenue lors de la suppression de l'instance!\nVeuillez reessayer!",
                                    type: 'error',
                                    button: "OK"
                                });
                            }
                        });
                    });
                },
                allowOutsideClick: false
            });
        }

        /*function reload() {
            {{--var url = "{{ route('instances.reload') }}";--}}
            $.ajax({
                url: url,
                type: "get",
                datatype: "html"
            }).done(function (data) {
                // append liste of directions to the table directions-table
                $('#tb_instances').empty().html(data);
                $('#tb_instances').DataTable().clear();
                $('#tb_instances').DataTable().destroy();
                var tab = $('#tb_instances').DataTable({
                    dom: 'lBfrtip',
                    responsive: true,
                    processing: true,
                    select: true,
                    "language": {
                        "url": "{{ asset('lang/datatables.french.json')}}"
                    },
                    buttons: [
                        'excelHtml5',
                        'pdfHtml5'
                    ],
                    "columnDefs": [{
                        "targets": 'no-sort',
                        "orderable": false,
                        "searchable": false
                    }]
                });
            }).fail(function (jqXHR, ajaxOptions, thrownError) {
                var prom = ezBSAlert({
                    messageText: "No response from server on load Error : " + thrownError,
                    alertType: "danger"
                });
            });
        }*/
    </script>
@endsection

@section('modal')
    {{--MODAL AJOUT & EDIT instance--}}
    @include('backend.instances.modalAddInstance')

    {{--MODAL MAJ Details--}}
    @include('backend.instances.modalDetail')
@endsection

resources/views/backend/instances/modalDetail.blade.php
<div class="modal fade my-5" id="modalDetail" tabindex="-1" role="dialog"
     aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <table class="table table-bordered table-sm table-striped table-hover">
                    <tbody id="contentActeurs">
                    <tr>
                        <th>Sigle</th>
                        <td id="libSigle"></td>
                        <th>Nom complet</th>
                        <td id="libNom"></td>
                    </tr>
                    <tr>
                        <th>Nombre de session</th>
                        <td id="libNbSession"></td>
                        <th>P&eacute;riodicit&eacute;</th>
                        <td id="libPeriodicite"></td>
                    </tr>
                    <tr>
                        <th>Ref. arr&ecirc;t&eacute; / d&eacute;cret</th>
                        <td id="libArr" colspan="3"></td>
                    </tr>
                    {{--<tr>
                        <th>Programme budg&eacute;taire</th>
                        <td id="libPbg" colspan="3"></td>
                    </tr>--}}
                    <tr>
                        <th>Description</th>
                        <td id="libDesc" colspan="3"></td>
                    </tr>
                    <tr>
                        <th>Crée le</th>
                        <td id="libCreatedAt"></td>
                        <th>Par</th>
                        <td id="libCreatedBy"></td>
                    </tr>
                    <tr>
                        <th>Modifié le</th>
                        <td id="libUpdatedAt"></td>
                        <th>Par</th>
                        <td id="libUpdatedBy"></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer" style="cursor: pointer;">
                <button type="button" data-dismiss="modal" class="btn btn-sm btn-danger">Fermer</button>
            </div>
        </div>
    </div>
</div>

resources/views/backend/instances/show.blade.php
@extends('layouts.template')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('instances.index') }}">Instance</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 {{-- @include('coreui-templates::common.errors') --}}
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('instances.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('backend.instances.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection