routes/web.php
    Route::get('deleteAgent/{id_agent}', 'AgentsController@deleteAgent')->name('deleteAgent');
    Route::get('getStructure/{id_structure}', 'StructuresController@getStructure')->name('getStructure');
    Route::get('getCategorie/{id_categorie}', 'CategoriesController@getCategorie')->name('getCategorie');
    Route::get('getAgent/{id_agent}', 'AgentsController@getAgent')->name('getAgent');
    Route::resource('templatemsgs', 'TemplatemsgsController');

    //routes for template
    Route::post('templatemsgs/save', 'TemplatemsgsController@save')->name('saveTemplate');
    Route::post('templatemsgs/updating/{id}', 'TemplatemsgsController@updating')->name('UpdatingTemplate');
    Route::get('templatemsgs/delete/{id}', 'TemplatemsgsController@delete')->name('deleteTemplate');
    Route::get('params/structure', 'TemplatemsgsController@listeStructure')->name('paramsStructure');
    Route::get('templatemsgs/detail/{id}', 'TemplatemsgsController@detailTemplate')->name('detailTemplate');
    Route::get('getTemplate/{id}', 'TemplatemsgsController@getTemplate')->name('getTemplate');
    //fin routes for template

    //debut route for alerts
    Route::get('instance/getSession/{id}', 'AlertesController@getSession')->name('getSession');
    Route::get('getModele', 'AlertesController@getModele')->name('getModele');
    Route::post('alertes/save', 'AlertesController@save')->name('SaveSession');
    Route::get('deleteAlerte/{id}', 'AlertesController@delete')->name('deleteAlerte');
    Route::get('getAlerte/{id}', 'AlertesController@getAlerte')->name('getAlerte');
    Route::post('alerte/updating/{id}', 'AlertesController@updating')->name('UpdateAlerte');
    Route::get('ConsulterMessage/{id}', 'AlertesController@ConsulterMessage')->name('ConsulterMessage');
    Route::get('filtreAlerte', 'AlertesController@filtreAlerteMessage')->name('filtreAlerte');
    Route::get('sendAlerte/{id}', 'EnvoiAlertesController@sendAlerte')->name('sendAlerte');
    Route::get('resendAlerte/{id}', 'EnvoiAlertesController@resendAlerte')->name('resendAlerte');
    Route::get('alertSearch', 'AlertesController@alertSearch')->name('alertSearch');
    Route::get('alerte/boiteReception', 'AlertesController@alertInbox')->name('alertInbox');
    Route::get('alerte/boiteReception/detail/{id}', 'AlertesController@infoAlerte')->name('alertInfo');
    Route::get('getMsg/{id}', 'AlertesController@getMsg')->name('getMsg');
    Route::get('alerte/listMessage/{id}', 'AlertesController@listEnvoi')->name('listMessage');
    Route::get('alertMessageSearch/', 'AlertesController@alertMessageSearch')->name('alertMessageSearch');
    //fin route for alerts

    //routes for envoiealertes
    Route::get('sendAlerte/{id}', 'EnvoiAlertesController@sendAlerte')->name('sendAlerte');
    Route::get('ListeEmailNotSend', 'EnvoiAlertesController@ListeEmailNotSend')->name('ListeEmailNotSend');
    Route::get('alerting', 'EnvoiAlertesController@alerting')->name('notifr'); //route pour tester seulement
    //
    Route::resource('alertes', 'AlertesController');
    Route::get('getPageAlertesSession/{id_session}', 'AlertesController@getPageAlertesSession')->name('getPageAlertesSession');

    Route::resource('participants', 'ParticipantsController');
    Route::get('getPageParticipantsSession/{id_session}', 'ParticipantsController@getPageParticipantsSession')->name('getPageParticipantsSession');

    Route::resource('recommandations', 'RecommandationsController');
    Route::get('getPageRecosBySession/{id_session}', 'RecommandationsController@getPageRecosBySession')->name('getPageRecosBySession');
    Route::get('getPageSaisieRecos', 'RecommandationsController@getPageSaisieRecos')->name('getPageSaisieRecos');
    Route::get('getPagePlaningRecos', 'RecommandationsController@getPagePlaningRecos', 'RecommandationsController@getPagePlaningRecos')->name('getPagePlaningRecos');
    Route::get('getPageSuiviRecos', 'RecommandationsController@getPageSuiviRecos')->name('getPageSuiviRecos');
    Route::get('getPageActiviteReco/{id_reco}', 'RecommandationsController@getPageActiviteReco')->name('getPageActiviteReco');
    Route::post('saveReco', 'RecommandationsController@saveReco')->name('saveReco');
    Route::post('modifierObservationReco', 'RecommandationsController@modifierObservationReco')->name('modifierObservationReco');
    Route::get('recosSearch', 'RecommandationsController@recosSearch')->name('recosSearch');
    Route::get('recosSearchForUserConnect', 'RecommandationsController@recosSearchForUserConnect')->name('recosSearchForUserConnect');
    Route::post('validerPlanningReco/{id_reco}', 'RecommandationsController@validerPlanningReco')->name('validerPlanningReco');
    Route::post('validerSuiviReco/{id_reco}', 'RecommandationsController@validerSuiviReco')->name('validerSuiviReco');
    Route::post('abandonnerReco/{id_reco}/{motif}', 'RecommandationsController@abandonnerReco')->name('abandonnerReco');
    Route::post('changerModeSuivi/{id_reco}/{value}', 'RecommandationsController@changerModeSuivi')->name('changerModeSuivi');
    Route::post('doSuiviReco/{id_reco}', 'RecommandationsController@doSuiviReco')->name('doSuiviReco');
    Route::get('getReco/{id_reco}', 'RecommandationsController@getReco')->name('getReco');
    Route::get('getAllRecos', 'Recommandat²ionsController@getAllRecos')->name('getAllRecos');
    Route::get('deleteReco/{id_reco}', 'RecommandationsController@deleteReco')->name('deleteReco');
    Route::get('deleteReco/{id_reco}', 'RecommandationsController@deleteReco')->name('deleteReco');
    Route::post('importRecos', 'RecommandationsController@importer')->name('importRecos');
    Route::get('downloadTemplateImport', 'RecommandationsController@downloadTemplateImport')->name('downloadTemplateImport');
    Route::get('getDataByInstanceByStructure/{ins_id}', 'RecommandationsController@getChartDataByInstanceByStructure')->name('getDataByInstanceByStructure');
    Route::get('getDataByInstance/{ins_id}', 'RecommandationsController@getChartDataByInstance')->name('getDataByInstance');
    Route::get('getDataAllInstanceByStructure', 'RecommandationsController@getChartDataAllInstanceByStructure')->name('getDataAllInstanceByStructure');
    Route::get('getDataAllInstance', 'RecommandationsController@getChartDataAllInstance')->name('getDataAllInstance');

    Route::resource('activites', 'ActivitesController');
    Route::post('saveActivite', 'ActivitesController@saveActivite')->name('saveActivite');
    Route::get('getActivite/{id_activite}', 'ActivitesController@getActivite')->name('getActivite');
    Route::get('deleteActivite', 'ActivitesController@deleteActivite')->name('deleteActivite');
    Route::get('deleteActivite/{id_partenaire}', 'ActivitesController@deleteActivite')->name('deleteActivite');
    Route::post('doSuiviActivite/{id_activite}', 'ActivitesController@doSuiviActivite')->name('doSuiviActivite');

    Route::resource('partenaires', 'PartenairesController');
    Route::get('getPagePartenaireReco/{id_reco}', 'PartenairesController@getPagePartenaireReco')->name('getPagePartenaireReco');
    Route::get('getListPartenairesByReco/{id_reco}', 'PartenairesController@getListPartenairesByReco')->name('getListPartenairesByReco');
    Route::post('savePartenaire', 'PartenairesController@savePartenaire')->name('savePartenaire');
    Route::get('getPartenaire/{id_partenaire}', 'PartenairesController@getPartenaire')->name('getPartenaire');
    Route::get('getAllPartenaires', 'PartenairesController@getAllPartenaires')->name('getAllPartenaires');
    Route::get('deletePartenaire/{id_partenaire}', 'PartenairesController@deletePartenaire')->name('deletePartenaire');
    Route::get('setResponsable/{id_partenaire}', 'PartenairesController@setResponsable')->name('setResponsable');

    Route::group(['middleware' => ['permission:CONSULTER_RAPPORT']], function () {
        Route::get('rapport', 'RapportController@index')->name('rapport.index');
        Route::post('rapportSearch', 'RapportController@rapportSearch')->name('rapportSearch')->middleware(['permission:CONSULTER_RAPPORT']);
        Route::get('getListPartenaires/{id_reco}', 'RapportController@getListPartenaires')->name('getListPartenaires');
        Route::get('getListActivites/{id_reco}', 'RapportController@getListActivites')->name('getListActivites');
        Route::get('getSessionsByInstance/{id_ins?}/{annee?}', 'RapportController@getSessionsByInstance')->name('getSessionsByInstance');
        Route::get('getActeursByInstance/{id_ins?}', 'RapportController@getActeursByInstance')->name('getActeursByInstance');
    });
    // routes des statistiques
    Route::group(['middleware' => ['permission:CONSULTER_STATS']], function () {
        Route::get('statistiques', 'StatistiquesController@index')->name('statistiques.index');
        Route::post('statistiqueSearch', 'StatistiquesController@statistiqueSearch')->name('statistiqueSearch');
        Route::get('getSessionsByInstance/{id_ins?}/{annee?}', 'RapportController@getSessionsByInstance')->name('getSessionsByInstance');
        Route::get('getActeursByInstance/{id_ins?}', 'RapportController@getActeursByInstance')->name('getActeursByInstance');
    });

    Route::resource('listeAlertes', 'ListeAlertesController');
    Route::resource('envoiAlertes', 'EnvoiAlertesController');

    Route::resource('programmeBudgetaires', 'ProgrammeBudgetairesController');
    Route::post('saveProgBug', 'ProgrammeBudgetairesController@saveProgBug')->name('saveProgBug');
    Route::get('getProgBug/{id_prog}', 'ProgrammeBudgetairesController@getProgBug')->name('getProgBug');
    Route::get('getAllProgBugs', 'ProgrammeBudgetairesController@getAllProgBugs')->name('getAllProgBugs');
    Route::get('deleteProgBug/{id_prog}', 'ProgrammeBudgetairesController@deleteProgBug')->name('deleteProgBug');
    Route::get('progBudgetaires/reload', 'ProgrammeBudgetairesController@reload')->name('progBudgetaires.reload');

app/Models/Activites.php
<?php

namespace App\Models;

use Eloquent as Model;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * Class Activites
 * @package App\Models
 * @version February 26, 2020, 1:29 pm UTC
 *
 * @property integer rec_id
 * @property integer ptn_id
 * @property string act_description
 * @property integer act_is_realise
 * @property integer act_is_valide
 * @property integer act_poids
 * @property string act_date_prevue
 * @property string act_date_realise
 * @property string act_preuve
 * @property string act_observation
 * @property string created_by
 * @property string updated_by
 */
class Activites extends Model
{

    use LogsActivity;
    public $table = 'activites';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';



    protected $primaryKey = 'act_id';

    public $fillable = [
        'rec_id',
        'ptn_id',
        'act_description',
        'act_is_realise',
        'act_is_valide',
        'act_poids',
        'act_date_prevue',
        'act_date_realise',
        'act_preuve',
        'act_observation',
        'created_by',
        'updated_by'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'act_id' => 'integer',
        'rec_id' => 'integer',
        'ptn_id' => 'integer',
        'act_description' => 'string',
        'act_is_realise' => 'integer',
        'act_is_valide' => 'integer',
        'act_poids' => 'integer',
        'act_date_prevue' => 'date',
        'act_date_realise' => 'date',
        'act_preuve' => 'string',
        'act_observation' => 'string',
        'created_by' => 'string',
        'updated_by' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'rec_id' => 'required',
        'ptn_id' => 'required',
        'act_description' => 'required',
        'act_is_realise' => 'required',
        'act_is_valide' => 'required',
        'created_by' => 'required',
        'created_at' => 'required'
    ];

    protected static $logName = 'Activités';
    public function getDescriptionForEvent(string $eventName): string
    {
        if ($eventName == 'created') {
            return "Création";
        } elseif ($eventName == 'updated') {
            return "Modification";
        } elseif ($eventName == 'deleted') {
            return "Suppression";
        }
    } 
    
}

resources/views/backend/activites/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('activites.index') !!}">Activites</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Activites</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'activites.store']) !!}

                                   @include('backend.activites.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/backend/activites/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('activites.index') !!}">Activites</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Activites</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($activites, ['route' => ['activites.update', $activites->act_id], 'method' => 'patch']) !!}

                              @include('backend.activites.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/backend/activites/fields.blade.php
<!-- Rec Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rec_id', 'Rec Id:') !!}
    {!! Form::number('rec_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Ptn Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ptn_id', 'Ptn Id:') !!}
    {!! Form::number('ptn_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Act Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('act_description', 'Act Description:') !!}
    {!! Form::textarea('act_description', null, ['class' => 'form-control']) !!}
</div>

<!-- Act Is Realise Field -->
<div class="form-group col-sm-6">
    {!! Form::label('act_is_realise', 'Act Is Realise:') !!}
    {!! Form::number('act_is_realise', null, ['class' => 'form-control']) !!}
</div>

<!-- Act Is Valide Field -->
<div class="form-group col-sm-6">
    {!! Form::label('act_is_valide', 'Act Is Valide:') !!}
    {!! Form::number('act_is_valide', null, ['class' => 'form-control']) !!}
</div>

<!-- Act Poids Field -->
<div class="form-group col-sm-6">
    {!! Form::label('act_poids', 'Act Poids:') !!}
    {!! Form::number('act_poids', null, ['class' => 'form-control']) !!}
</div>

<!-- Act Date Prevue Field -->
<div class="form-group col-sm-6">
    {!! Form::label('act_date_prevue', 'Act Date Prevue:') !!}
    {!! Form::text('act_date_prevue', null, ['class' => 'form-control','id'=>'act_date_prevue']) !!}
</div>

@push('scripts')
   <script type="text/javascript">
           $('#act_date_prevue').datetimepicker({
               format: 'YYYY-MM-DD HH:mm:ss',
               useCurrent: true,
               icons: {
                   up: "icon-arrow-up-circle icons font-2xl",
                   down: "icon-arrow-down-circle icons font-2xl"
               },
               sideBySide: true
           })
       </script>
@endpush


<!-- Act Date Realise Field -->
<div class="form-group col-sm-6">
    {!! Form::label('act_date_realise', 'Act Date Realise:') !!}
    {!! Form::text('act_date_realise', null, ['class' => 'form-control','id'=>'act_date_realise']) !!}
</div>

@push('scripts')
   <script type="text/javascript">
           $('#act_date_realise').datetimepicker({
               format: 'YYYY-MM-DD HH:mm:ss',
               useCurrent: true,
               icons: {
                   up: "icon-arrow-up-circle icons font-2xl",
                   down: "icon-arrow-down-circle icons font-2xl"
               },
               sideBySide: true
           })
       </script>
@endpush


<!-- Act Preuve Field -->
<div class="form-group col-sm-6">
    {!! Form::label('act_preuve', 'Act Preuve:') !!}
    {!! Form::text('act_preuve', null, ['class' => 'form-control']) !!}
</div>

<!-- Created By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('created_by', 'Created By:') !!}
    {!! Form::text('created_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Updated By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('updated_by', 'Updated By:') !!}
    {!! Form::text('updated_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('activites.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/backend/activites/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Activites</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Activites
                             <a class="pull-right" href="{{ route('activites.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('backend.activites.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/backend/activites/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('activites.index') }}">Activites</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('activites.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('backend.activites.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/backend/activites/show_fields.blade.php
<!-- Rec Id Field -->
<div class="form-group">
    {!! Form::label('rec_id', 'Rec Id:') !!}
    <p>{{ $activites->rec_id }}</p>
</div>

<!-- Ptn Id Field -->
<div class="form-group">
    {!! Form::label('ptn_id', 'Ptn Id:') !!}
    <p>{{ $activites->ptn_id }}</p>
</div>

<!-- Act Description Field -->
<div class="form-group">
    {!! Form::label('act_description', 'Act Description:') !!}
    <p>{{ $activites->act_description }}</p>
</div>

<!-- Act Is Realise Field -->
<div class="form-group">
    {!! Form::label('act_is_realise', 'Act Is Realise:') !!}
    <p>{{ $activites->act_is_realise }}</p>
</div>

<!-- Act Is Valide Field -->
<div class="form-group">
    {!! Form::label('act_is_valide', 'Act Is Valide:') !!}
    <p>{{ $activites->act_is_valide }}</p>
</div>

<!-- Act Poids Field -->
<div class="form-group">
    {!! Form::label('act_poids', 'Act Poids:') !!}
    <p>{{ $activites->act_poids }}</p>
</div>

<!-- Act Date Prevue Field -->
<div class="form-group">
    {!! Form::label('act_date_prevue', 'Act Date Prevue:') !!}
    <p>{{ $activites->act_date_prevue }}</p>
</div>

<!-- Act Date Realise Field -->
<div class="form-group">
    {!! Form::label('act_date_realise', 'Act Date Realise:') !!}
    <p>{{ $activites->act_date_realise }}</p>
</div>

<!-- Act Preuve Field -->
<div class="form-group">
    {!! Form::label('act_preuve', 'Act Preuve:') !!}
    <p>{{ $activites->act_preuve }}</p>
</div>

<!-- Created By Field -->
<div class="form-group">
    {!! Form::label('created_by', 'Created By:') !!}
    <p>{{ $activites->created_by }}</p>
</div>

<!-- Updated By Field -->
<div class="form-group">
    {!! Form::label('updated_by', 'Updated By:') !!}
    <p>{{ $activites->updated_by }}</p>
</div>

resources/views/backend/activites/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="activites-table">
        <thead>
            <th>Rec Id</th>
        <th>Ptn Id</th>
        <th>Act Description</th>
        <th>Act Is Realise</th>
        <th>Act Is Valide</th>
        <th>Act Poids</th>
        <th>Act Date Prevue</th>
        <th>Act Date Realise</th>
        <th>Act Preuve</th>
        <th>Created By</th>
        <th>Updated By</th>
            <th colspan="3">Action</th>
        </thead>
        <tbody>
        @foreach($activites as $activites)
            <tr>
                <td>{{ $activites->rec_id }}</td>
            <td>{{ $activites->ptn_id }}</td>
            <td>{{ $activites->act_description }}</td>
            <td>{{ $activites->act_is_realise }}</td>
            <td>{{ $activites->act_is_valide }}</td>
            <td>{{ $activites->act_poids }}</td>
            <td>{{ $activites->act_date_prevue }}</td>
            <td>{{ $activites->act_date_realise }}</td>
            <td>{{ $activites->act_preuve }}</td>
            <td>{{ $activites->created_by }}</td>
            <td>{{ $activites->updated_by }}</td>
                <td>
                    {!! Form::open(['route' => ['activites.destroy', $activites->act_id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('activites.show', [$activites->act_id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('activites.edit', [$activites->act_id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>