routes/web.php
    Route::resource('instances', 'InstanceController');
    Route::post('saveInstance', 'InstanceController@saveInstance')->name('saveInstance');
    Route::get('getInstance/{id_instance}', 'InstanceController@getInstance')->name('getInstance');
    Route::get('getAllInstances', 'InstanceController@getAllInstances')->name('getAllInstances');
    Route::get('getAllInstancesCSS', 'InstanceController@getAllInstancesCSS')->name('getAllInstancesCSS');
    Route::get('deleteInstance/{id_instance}', 'InstanceController@deleteInstance')->name('deleteInstance');
    Route::get('supprimerProfil/{id_role}', 'RolesController@supprimerProfil')->name('supprimerProfil');

    Route::resource('sessions', 'SessionController');
    Route::post('saveSession', 'SessionController@saveSession')->name('saveSession');
    Route::post('changeStatus/{id_session}/{value}', 'SessionController@changeStatus')->name('changeStatus');
    Route::get('sessionsSearch', 'SessionController@sessionsSearch')->name('sessionsSearch');
    Route::get('structuresWhereRecoNotPlan/{ses_id}', 'SessionController@structuresWhereRecoNotPlan')->name('structuresWhereRecoNotPlan');
    Route::post('joindreListParticipant', 'SessionController@joindreListParticipant')->name('joindreListParticipant');
    Route::get('getSession/{id_session}', 'SessionController@getSession')->name('getSession');
    Route::get('getAllSessions', 'SessionController@getAllSessions')->name('getAllSessions');
    Route::get('getAllSessionsEnFormulation', 'SessionController@getAllSessionsEnFormulation')->name('getAllSessionsEnFormulation');
    Route::get('deleteSession/{id_session}', 'SessionController@deleteSession')->name('deleteSession');
    Route::get('getRecosAreconduire/{ses_id_precedant}', 'SessionController@getRecosAreconduire')->name('getRecosAreconduire');
    Route::post('reconduireRecos', 'SessionController@reconduireRecos')->name('reconduireRecos');
    //    Route::get('reconduireRecos/{ses_id}/{ses_id_precedant}', 'SessionController@reconduireRecos')->name('reconduireRecos');

    
    Route::get('usersSearch', 'UsersController@usersSearch')->name('usersSearch');
    Route::get('deleteAgent/{id_agent}', 'AgentsController@deleteAgent')->name('deleteAgent');
    Route::get('getStructure/{id_structure}', 'StructuresController@getStructure')->name('getStructure');
    Route::get('getCategorie/{id_categorie}', 'CategoriesController@getCategorie')->name('getCategorie');
    Route::get('getAgent/{id_agent}', 'AgentsController@getAgent')->name('getAgent');
    Route::resource('templatemsgs', 'TemplatemsgsController');

    //routes for template
    Route::post('templatemsgs/save', 'TemplatemsgsController@save')->name('saveTemplate');
    Route::post('templatemsgs/updating/{id}', 'TemplatemsgsController@updating')->name('UpdatingTemplate');
    Route::get('templatemsgs/delete/{id}', 'TemplatemsgsController@delete')->name('deleteTemplate');
    Route::get('params/structure', 'TemplatemsgsController@listeStructure')->name('paramsStructure');
    Route::get('templatemsgs/detail/{id}', 'TemplatemsgsController@detailTemplate')->name('detailTemplate');
    Route::get('getTemplate/{id}', 'TemplatemsgsController@getTemplate')->name('getTemplate');
    //fin routes for template

    //debut route for alerts
    Route::get('instance/getSession/{id}', 'AlertesController@getSession')->name('getSession');
    Route::get('getModele', 'AlertesController@getModele')->name('getModele');
    Route::post('alertes/save', 'AlertesController@save')->name('SaveSession');
    Route::get('deleteAlerte/{id}', 'AlertesController@delete')->name('deleteAlerte');
    Route::get('getAlerte/{id}', 'AlertesController@getAlerte')->name('getAlerte');
    Route::post('alerte/updating/{id}', 'AlertesController@updating')->name('UpdateAlerte');
    Route::get('ConsulterMessage/{id}', 'AlertesController@ConsulterMessage')->name('ConsulterMessage');
    Route::get('filtreAlerte', 'AlertesController@filtreAlerteMessage')->name('filtreAlerte');
    Route::get('sendAlerte/{id}', 'EnvoiAlertesController@sendAlerte')->name('sendAlerte');
    Route::get('resendAlerte/{id}', 'EnvoiAlertesController@resendAlerte')->name('resendAlerte');
    Route::get('alertSearch', 'AlertesController@alertSearch')->name('alertSearch');
    Route::get('alerte/boiteReception', 'AlertesController@alertInbox')->name('alertInbox');
    Route::get('alerte/boiteReception/detail/{id}', 'AlertesController@infoAlerte')->name('alertInfo');
    Route::get('getMsg/{id}', 'AlertesController@getMsg')->name('getMsg');
    Route::get('alerte/listMessage/{id}', 'AlertesController@listEnvoi')->name('listMessage');
    Route::get('alertMessageSearch/', 'AlertesController@alertMessageSearch')->name('alertMessageSearch');
    //fin route for alerts

    //routes for envoiealertes
    Route::get('sendAlerte/{id}', 'EnvoiAlertesController@sendAlerte')->name('sendAlerte');
    Route::get('ListeEmailNotSend', 'EnvoiAlertesController@ListeEmailNotSend')->name('ListeEmailNotSend');
    Route::get('alerting', 'EnvoiAlertesController@alerting')->name('notifr'); //route pour tester seulement
    //
    Route::resource('alertes', 'AlertesController');
    Route::get('getPageAlertesSession/{id_session}', 'AlertesController@getPageAlertesSession')->name('getPageAlertesSession');

    Route::resource('participants', 'ParticipantsController');
    Route::get('getPageParticipantsSession/{id_session}', 'ParticipantsController@getPageParticipantsSession')->name('getPageParticipantsSession');

    Route::resource('recommandations', 'RecommandationsController');
    Route::get('getPageRecosBySession/{id_session}', 'RecommandationsController@getPageRecosBySession')->name('getPageRecosBySession');
    Route::get('getPageSaisieRecos', 'RecommandationsController@getPageSaisieRecos')->name('getPageSaisieRecos');
    Route::get('getPagePlaningRecos', 'RecommandationsController@getPagePlaningRecos', 'RecommandationsController@getPagePlaningRecos')->name('getPagePlaningRecos');
    Route::get('getPageSuiviRecos', 'RecommandationsController@getPageSuiviRecos')->name('getPageSuiviRecos');
    Route::get('getPageActiviteReco/{id_reco}', 'RecommandationsController@getPageActiviteReco')->name('getPageActiviteReco');
    Route::post('saveReco', 'RecommandationsController@saveReco')->name('saveReco');
    Route::post('modifierObservationReco', 'RecommandationsController@modifierObservationReco')->name('modifierObservationReco');
    Route::get('recosSearch', 'RecommandationsController@recosSearch')->name('recosSearch');
    Route::get('recosSearchForUserConnect', 'RecommandationsController@recosSearchForUserConnect')->name('recosSearchForUserConnect');
    Route::post('validerPlanningReco/{id_reco}', 'RecommandationsController@validerPlanningReco')->name('validerPlanningReco');
    Route::post('validerSuiviReco/{id_reco}', 'RecommandationsController@validerSuiviReco')->name('validerSuiviReco');
    Route::post('abandonnerReco/{id_reco}/{motif}', 'RecommandationsController@abandonnerReco')->name('abandonnerReco');
    Route::post('changerModeSuivi/{id_reco}/{value}', 'RecommandationsController@changerModeSuivi')->name('changerModeSuivi');
    Route::post('doSuiviReco/{id_reco}', 'RecommandationsController@doSuiviReco')->name('doSuiviReco');
    Route::get('getReco/{id_reco}', 'RecommandationsController@getReco')->name('getReco');
    Route::get('getAllRecos', 'Recommandat²ionsController@getAllRecos')->name('getAllRecos');
    Route::get('deleteReco/{id_reco}', 'RecommandationsController@deleteReco')->name('deleteReco');
    Route::get('deleteReco/{id_reco}', 'RecommandationsController@deleteReco')->name('deleteReco');
    Route::post('importRecos', 'RecommandationsController@importer')->name('importRecos');
    Route::get('downloadTemplateImport', 'RecommandationsController@downloadTemplateImport')->name('downloadTemplateImport');
    Route::get('getDataByInstanceByStructure/{ins_id}', 'RecommandationsController@getChartDataByInstanceByStructure')->name('getDataByInstanceByStructure');
    Route::get('getDataByInstance/{ins_id}', 'RecommandationsController@getChartDataByInstance')->name('getDataByInstance');
    Route::get('getDataAllInstanceByStructure', 'RecommandationsController@getChartDataAllInstanceByStructure')->name('getDataAllInstanceByStructure');
    Route::get('getDataAllInstance', 'RecommandationsController@getChartDataAllInstance')->name('getDataAllInstance');

    Route::resource('activites', 'ActivitesController');
    Route::post('saveActivite', 'ActivitesController@saveActivite')->name('saveActivite');
    Route::get('getActivite/{id_activite}', 'ActivitesController@getActivite')->name('getActivite');
    Route::get('deleteActivite', 'ActivitesController@deleteActivite')->name('deleteActivite');
    Route::get('deleteActivite/{id_partenaire}', 'ActivitesController@deleteActivite')->name('deleteActivite');
    Route::post('doSuiviActivite/{id_activite}', 'ActivitesController@doSuiviActivite')->name('doSuiviActivite');

    Route::resource('partenaires', 'PartenairesController');
    Route::get('getPagePartenaireReco/{id_reco}', 'PartenairesController@getPagePartenaireReco')->name('getPagePartenaireReco');
    Route::get('getListPartenairesByReco/{id_reco}', 'PartenairesController@getListPartenairesByReco')->name('getListPartenairesByReco');
    Route::post('savePartenaire', 'PartenairesController@savePartenaire')->name('savePartenaire');
    Route::get('getPartenaire/{id_partenaire}', 'PartenairesController@getPartenaire')->name('getPartenaire');
    Route::get('getAllPartenaires', 'PartenairesController@getAllPartenaires')->name('getAllPartenaires');
    Route::get('deletePartenaire/{id_partenaire}', 'PartenairesController@deletePartenaire')->name('deletePartenaire');
    Route::get('setResponsable/{id_partenaire}', 'PartenairesController@setResponsable')->name('setResponsable');

    Route::group(['middleware' => ['permission:CONSULTER_RAPPORT']], function () {

app/Models/Alertes.php
<?php

namespace App\Models;

use Eloquent as Model;
use Spatie\Activitylog\Traits\LogsActivity;


/**
 * Class Alertes
 * @package App\Models
 * @version February 24, 2020, 10:13 am UTC
 *
 * @property integer ses_id
 * @property integer tmsg_id
 * @property string ale_msg
 * @property string|\Carbon\Carbon ale_date_heure_prev
 * @property integer ale_etat
 * @property string ale_tmsg_type
 * @property string|\Carbon\Carbon ale_date_heure_envoi
 * @property string created_by
 * @property string updated_by
 */
class Alertes extends Model
{

   // use LogsActivity;
    public $table = 'alertes';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';



    protected $primaryKey = 'ale_id';

    public $fillable = [
        'ses_id',
        'tmsg_id',
        'ale_msg',
        'ale_date_heure_prev',
        'ale_etat',
        'ale_tmsg_type',
        'ale_date_heure_envoi',
        'created_by',
        'updated_by'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'ale_id' => 'integer',
        'ses_id' => 'integer',
        'tmsg_id' => 'integer',
        'ale_msg' => 'string',
        'ale_date_heure_prev' => 'dateTime',
        'ale_etat' => 'integer',
        'ale_tmsg_type' => 'string',
        'ale_date_heure_envoi' => 'dateTime',
        'created_by' => 'string',
        'updated_by' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'ses_id' => 'required',
        'tmsg_id' => 'required',
        'ale_msg' => 'required',
        'ale_date_heure_prev' => 'required',
        'ale_etat' => 'required',
        'ale_tmsg_type' => 'required',
        'created_by' => 'required',
        'created_at' => 'required'
    ];




}

resources/views/backend/alertes/AlertMessage.blade.php
@extends('layouts.template')

@section('title')
    Alert
    @parent
@stop

@section('content')
    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#"><i class="cib-co-op"></i>Alerte</a></li>
                <li class="breadcrumb-item"><a href="#"><i class="cib-co-op"></i>Notifications</a></li>
				<li class="breadcrumb-item"><a href="#"><i class="cib-co-op"></i>Boîte d'envois</a></li>
                <li class="breadcrumb-item active" aria-current="page">Détails</li>
            </ol>
        </nav>

        <div class="row mb-3">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-header widget-content">
                        <div class="widget-content-wrapper">
                            <div class="widget-content-left">
                                <div class="card-title"><strong> Détail de la notification </strong><span style="color:#0073e6">{{$envoi->ale_mail_subject}}&nbsp;&nbsp;-&nbsp;&nbsp;</span><span style="color:#ffcc00">reçu le {{ $envoi->ena_date_heure_recu->format('d/m/Y à H:i:s')}}</span></div>
                            </div>
                            <div class="widget-content-right">
                                <button onclick="goBack()" class="float-right btn btn-sm btn-warning">
                                    <i class="fa fa-arrow-left"></i>&nbsp;&nbsp;Retour
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="content">
                            <div class="portlet box default" style="margin-top: 10px">
                                <div class="portlet-body flip-scroll">
                                    <div class="row justify-content-center">
                                        <div class="col-md-12">
											<div class="row">
													<div class="col-md-6"><strong>Session concernée ({{$envoi->ena_ses_annee}})</strong>&nbsp;:&nbsp;{{$envoi->ena_ses_description}} - du {{$envoi->ena_ses_debut->format('d/m/Y')}} au {{$envoi->ena_ses_fin->format('d/m/Y')}} à {{$envoi->ena_ses_lieu}}<hr></div>
													
													<div class="col-md-6"><strong>Destinataire</strong>&nbsp;:&nbsp;{{$envoi->str_sigle}} > {{$envoi->user_nom}} {{$envoi->user_prenom}} < {{$envoi->user_email}} ><hr></div>
											</div>
											<div class="row">
												<div class="col-md-12"><strong>Contenu de la notification :</strong></div>
											</div>
											<div class="row">
												<div class="col-md-12">{!!$envoi->ena_msg  !!}</div> 
											</div>
											
                                        </div>
                                        
                                    </div>
                                    
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/alertes/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('alertes.index') !!}">Alertes</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Alertes</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'alertes.store']) !!}

                                   @include('backend.alertes.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/backend/alertes/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('alertes.index') !!}">Alertes</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Alertes</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($alertes, ['route' => ['alertes.update', $alertes->ale_id], 'method' => 'patch']) !!}

                              @include('backend.alertes.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/backend/alertes/fields.blade.php
<!-- Ses Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ses_id', 'Ses Id:') !!}
    {!! Form::number('ses_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Tmsg Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tmsg_id', 'Tmsg Id:') !!}
    {!! Form::number('tmsg_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Ale Msg Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ale_msg', 'Ale Msg:') !!}
    {!! Form::text('ale_msg', null, ['class' => 'form-control']) !!}
</div>

<!-- Ale Date Heure Prev Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ale_date_heure_prev', 'Ale Date Heure Prev:') !!}
    {!! Form::text('ale_date_heure_prev', null, ['class' => 'form-control','id'=>'ale_date_heure_prev']) !!}
</div>

@push('scripts')
   <script type="text/javascript">
           $('#ale_date_heure_prev').datetimepicker({
               format: 'YYYY-MM-DD HH:mm:ss',
               useCurrent: true,
               icons: {
                   up: "icon-arrow-up-circle icons font-2xl",
                   down: "icon-arrow-down-circle icons font-2xl"
               },
               sideBySide: true
           })
       </script>
@endpush


<!-- Ale Etat Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ale_etat', 'Ale Etat:') !!}
    {!! Form::number('ale_etat', null, ['class' => 'form-control']) !!}
</div>

<!-- Ale Tmsg Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ale_tmsg_type', 'Ale Tmsg Type:') !!}
    {!! Form::text('ale_tmsg_type', null, ['class' => 'form-control']) !!}
</div>

<!-- Ale Date Heure Envoi Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ale_date_heure_envoi', 'Ale Date Heure Envoi:') !!}
    {!! Form::text('ale_date_heure_envoi', null, ['class' => 'form-control','id'=>'ale_date_heure_envoi']) !!}
</div>

@push('scripts')
   <script type="text/javascript">
           $('#ale_date_heure_envoi').datetimepicker({
               format: 'YYYY-MM-DD HH:mm:ss',
               useCurrent: true,
               icons: {
                   up: "icon-arrow-up-circle icons font-2xl",
                   down: "icon-arrow-down-circle icons font-2xl"
               },
               sideBySide: true
           })
       </script>
@endpush


<!-- Created By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('created_by', 'Created By:') !!}
    {!! Form::text('created_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Updated By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('updated_by', 'Updated By:') !!}
    {!! Form::text('updated_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('alertes.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/backend/alertes/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('alertes.index') }}">Alertes</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('alertes.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('backend.alertes.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/backend/alertes/show_fields.blade.php
<!-- Ses Id Field -->
<div class="form-group">
    {!! Form::label('ses_id', 'Ses Id:') !!}
    <p>{{ $alertes->ses_id }}</p>
</div>

<!-- Tmsg Id Field -->
<div class="form-group">
    {!! Form::label('tmsg_id', 'Tmsg Id:') !!}
    <p>{{ $alertes->tmsg_id }}</p>
</div>

<!-- Ale Msg Field -->
<div class="form-group">
    {!! Form::label('ale_msg', 'Ale Msg:') !!}
    <p>{{ $alertes->ale_msg }}</p>
</div>

<!-- Ale Date Heure Prev Field -->
<div class="form-group">
    {!! Form::label('ale_date_heure_prev', 'Ale Date Heure Prev:') !!}
    <p>{{ $alertes->ale_date_heure_prev }}</p>
</div>

<!-- Ale Etat Field -->
<div class="form-group">
    {!! Form::label('ale_etat', 'Ale Etat:') !!}
    <p>{{ $alertes->ale_etat }}</p>
</div>

<!-- Ale Tmsg Type Field -->
<div class="form-group">
    {!! Form::label('ale_tmsg_type', 'Ale Tmsg Type:') !!}
    <p>{{ $alertes->ale_tmsg_type }}</p>
</div>

<!-- Ale Date Heure Envoi Field -->
<div class="form-group">
    {!! Form::label('ale_date_heure_envoi', 'Ale Date Heure Envoi:') !!}
    <p>{{ $alertes->ale_date_heure_envoi }}</p>
</div>

<!-- Created By Field -->
<div class="form-group">
    {!! Form::label('created_by', 'Created By:') !!}
    <p>{{ $alertes->created_by }}</p>
</div>

<!-- Updated By Field -->
<div class="form-group">
    {!! Form::label('updated_by', 'Updated By:') !!}
    <p>{{ $alertes->updated_by }}</p>
</div>

resources/views/backend/alertes/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped dt_exemple" id="alertes-table">
        <thead>
            <th>#</th>

        <th>Message</th>
        <th>Heure Prevue</th>
        <th>Etat</th>
        <th>Type</th>
        <th>Heure d'envoie</th>

            <th>Action</th>

        </thead>
        <tbody>
        @php($i=0)
        @foreach($alertes as $alertes)

            @php($i=$i+1)
            <tr>
                <td>{{ $i}}</td>
            <td>{{ $alertes->ale_msg }}</td>
            <td>{{ $alertes->ale_date_heure_prev }}</td>
            <td><span class="badge badge-pill badge-warning">{{$alertes->etat}}</span></td>
            <td>{{ $alertes->ale_tmsg_type }}</td>
            <td>{{ $alertes->ale_date_heure_envoi }}</td>

                <td>

                    <div class='btn-group'>

                            <button type="button" class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                Actions
                            </button>

                            <div class="dropdown-menu">
                                <button class='dropdown-item'
                                        data-toggle="modal" data-target="#modalDetailAlerte"  data-placement="top" title="Voir détail" onclick="openModalDetailAlerte({{ $alertes->ale_id }})">
                                    <i class="fa fa-eye"></i>&nbsp;&nbsp;Voir détails
                                </button>

                                <button class='dropdown-item' onclick="openModalAddAlerte({{ $alertes->ale_id }})"

                                        data-placement="top" title="modifier l'alerte"    data-toggle="modal" data-target="#modalAddAlerte">
                                    <i class="fa fa-edit"></i>&nbsp;&nbsp;Modifier
                                </button>
                                <button class='dropdown-item' onclick="deleteAlerte({{$alertes->ale_id}},'{{$alertes->ale_id}}')"
                                        data-placement="top" title="Supprimer l'alerte">

                                    <i class="fa fa-trash"></i>&nbsp;&nbsp;Supprimer
                                </button>
                                <button class='dropdown-item' onclick="deleteModele()"
                                        data-toggle="tooltip" data-placement="top" title="Envoyer l'alerte">

                                    <i class="fa fa-forward"></i>&nbsp;&nbsp;Envoyer
                                </button>
                            </div>
                        </div>


                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>