routes/web.php
    Route::get('deleteAgent/{id_agent}', 'AgentsController@deleteAgent')->name('deleteAgent');
    Route::get('getStructure/{id_structure}', 'StructuresController@getStructure')->name('getStructure');
    Route::get('getCategorie/{id_categorie}', 'CategoriesController@getCategorie')->name('getCategorie');
    Route::get('getAgent/{id_agent}', 'AgentsController@getAgent')->name('getAgent');
    Route::resource('templatemsgs', 'TemplatemsgsController');

    //routes for template
    Route::post('templatemsgs/save', 'TemplatemsgsController@save')->name('saveTemplate');
    Route::post('templatemsgs/updating/{id}', 'TemplatemsgsController@updating')->name('UpdatingTemplate');
    Route::get('templatemsgs/delete/{id}', 'TemplatemsgsController@delete')->name('deleteTemplate');
    Route::get('params/structure', 'TemplatemsgsController@listeStructure')->name('paramsStructure');
    Route::get('templatemsgs/detail/{id}', 'TemplatemsgsController@detailTemplate')->name('detailTemplate');
    Route::get('getTemplate/{id}', 'TemplatemsgsController@getTemplate')->name('getTemplate');
    //fin routes for template

    //debut route for alerts
    Route::get('instance/getSession/{id}', 'AlertesController@getSession')->name('getSession');
    Route::get('getModele', 'AlertesController@getModele')->name('getModele');
    Route::post('alertes/save', 'AlertesController@save')->name('SaveSession');
    Route::get('deleteAlerte/{id}', 'AlertesController@delete')->name('deleteAlerte');
    Route::get('getAlerte/{id}', 'AlertesController@getAlerte')->name('getAlerte');
    Route::post('alerte/updating/{id}', 'AlertesController@updating')->name('UpdateAlerte');
    Route::get('ConsulterMessage/{id}', 'AlertesController@ConsulterMessage')->name('ConsulterMessage');
    Route::get('filtreAlerte', 'AlertesController@filtreAlerteMessage')->name('filtreAlerte');
    Route::get('sendAlerte/{id}', 'EnvoiAlertesController@sendAlerte')->name('sendAlerte');
    Route::get('resendAlerte/{id}', 'EnvoiAlertesController@resendAlerte')->name('resendAlerte');
    Route::get('alertSearch', 'AlertesController@alertSearch')->name('alertSearch');
    Route::get('alerte/boiteReception', 'AlertesController@alertInbox')->name('alertInbox');
    Route::get('alerte/boiteReception/detail/{id}', 'AlertesController@infoAlerte')->name('alertInfo');
    Route::get('getMsg/{id}', 'AlertesController@getMsg')->name('getMsg');
    Route::get('alerte/listMessage/{id}', 'AlertesController@listEnvoi')->name('listMessage');
    Route::get('alertMessageSearch/', 'AlertesController@alertMessageSearch')->name('alertMessageSearch');
    //fin route for alerts

    //routes for envoiealertes
    Route::get('sendAlerte/{id}', 'EnvoiAlertesController@sendAlerte')->name('sendAlerte');
    Route::get('ListeEmailNotSend', 'EnvoiAlertesController@ListeEmailNotSend')->name('ListeEmailNotSend');
    Route::get('alerting', 'EnvoiAlertesController@alerting')->name('notifr'); //route pour tester seulement
    //
    Route::resource('alertes', 'AlertesController');
    Route::get('getPageAlertesSession/{id_session}', 'AlertesController@getPageAlertesSession')->name('getPageAlertesSession');

    Route::resource('participants', 'ParticipantsController');
    Route::get('getPageParticipantsSession/{id_session}', 'ParticipantsController@getPageParticipantsSession')->name('getPageParticipantsSession');

    Route::resource('recommandations', 'RecommandationsController');
    Route::get('getPageRecosBySession/{id_session}', 'RecommandationsController@getPageRecosBySession')->name('getPageRecosBySession');
    Route::get('getPageSaisieRecos', 'RecommandationsController@getPageSaisieRecos')->name('getPageSaisieRecos');
    Route::get('getPagePlaningRecos', 'RecommandationsController@getPagePlaningRecos', 'RecommandationsController@getPagePlaningRecos')->name('getPagePlaningRecos');
    Route::get('getPageSuiviRecos', 'RecommandationsController@getPageSuiviRecos')->name('getPageSuiviRecos');
    Route::get('getPageActiviteReco/{id_reco}', 'RecommandationsController@getPageActiviteReco')->name('getPageActiviteReco');
    Route::post('saveReco', 'RecommandationsController@saveReco')->name('saveReco');
    Route::post('modifierObservationReco', 'RecommandationsController@modifierObservationReco')->name('modifierObservationReco');
    Route::get('recosSearch', 'RecommandationsController@recosSearch')->name('recosSearch');
    Route::get('recosSearchForUserConnect', 'RecommandationsController@recosSearchForUserConnect')->name('recosSearchForUserConnect');
    Route::post('validerPlanningReco/{id_reco}', 'RecommandationsController@validerPlanningReco')->name('validerPlanningReco');
    Route::post('validerSuiviReco/{id_reco}', 'RecommandationsController@validerSuiviReco')->name('validerSuiviReco');
    Route::post('abandonnerReco/{id_reco}/{motif}', 'RecommandationsController@abandonnerReco')->name('abandonnerReco');
    Route::post('changerModeSuivi/{id_reco}/{value}', 'RecommandationsController@changerModeSuivi')->name('changerModeSuivi');
    Route::post('doSuiviReco/{id_reco}', 'RecommandationsController@doSuiviReco')->name('doSuiviReco');
    Route::get('getReco/{id_reco}', 'RecommandationsController@getReco')->name('getReco');
    Route::get('getAllRecos', 'Recommandat²ionsController@getAllRecos')->name('getAllRecos');
    Route::get('deleteReco/{id_reco}', 'RecommandationsController@deleteReco')->name('deleteReco');
    Route::get('deleteReco/{id_reco}', 'RecommandationsController@deleteReco')->name('deleteReco');
    Route::post('importRecos', 'RecommandationsController@importer')->name('importRecos');
    Route::get('downloadTemplateImport', 'RecommandationsController@downloadTemplateImport')->name('downloadTemplateImport');
    Route::get('getDataByInstanceByStructure/{ins_id}', 'RecommandationsController@getChartDataByInstanceByStructure')->name('getDataByInstanceByStructure');
    Route::get('getDataByInstance/{ins_id}', 'RecommandationsController@getChartDataByInstance')->name('getDataByInstance');
    Route::get('getDataAllInstanceByStructure', 'RecommandationsController@getChartDataAllInstanceByStructure')->name('getDataAllInstanceByStructure');
    Route::get('getDataAllInstance', 'RecommandationsController@getChartDataAllInstance')->name('getDataAllInstance');

    Route::resource('activites', 'ActivitesController');
    Route::post('saveActivite', 'ActivitesController@saveActivite')->name('saveActivite');
    Route::get('getActivite/{id_activite}', 'ActivitesController@getActivite')->name('getActivite');
    Route::get('deleteActivite', 'ActivitesController@deleteActivite')->name('deleteActivite');
    Route::get('deleteActivite/{id_partenaire}', 'ActivitesController@deleteActivite')->name('deleteActivite');
    Route::post('doSuiviActivite/{id_activite}', 'ActivitesController@doSuiviActivite')->name('doSuiviActivite');

    Route::resource('partenaires', 'PartenairesController');
    Route::get('getPagePartenaireReco/{id_reco}', 'PartenairesController@getPagePartenaireReco')->name('getPagePartenaireReco');
    Route::get('getListPartenairesByReco/{id_reco}', 'PartenairesController@getListPartenairesByReco')->name('getListPartenairesByReco');
    Route::post('savePartenaire', 'PartenairesController@savePartenaire')->name('savePartenaire');
    Route::get('getPartenaire/{id_partenaire}', 'PartenairesController@getPartenaire')->name('getPartenaire');
    Route::get('getAllPartenaires', 'PartenairesController@getAllPartenaires')->name('getAllPartenaires');
    Route::get('deletePartenaire/{id_partenaire}', 'PartenairesController@deletePartenaire')->name('deletePartenaire');
    Route::get('setResponsable/{id_partenaire}', 'PartenairesController@setResponsable')->name('setResponsable');

    Route::group(['middleware' => ['permission:CONSULTER_RAPPORT']], function () {
        Route::get('rapport', 'RapportController@index')->name('rapport.index');
        Route::post('rapportSearch', 'RapportController@rapportSearch')->name('rapportSearch')->middleware(['permission:CONSULTER_RAPPORT']);
        Route::get('getListPartenaires/{id_reco}', 'RapportController@getListPartenaires')->name('getListPartenaires');
        Route::get('getListActivites/{id_reco}', 'RapportController@getListActivites')->name('getListActivites');
        Route::get('getSessionsByInstance/{id_ins?}/{annee?}', 'RapportController@getSessionsByInstance')->name('getSessionsByInstance');
        Route::get('getActeursByInstance/{id_ins?}', 'RapportController@getActeursByInstance')->name('getActeursByInstance');
    });
    // routes des statistiques
    Route::group(['middleware' => ['permission:CONSULTER_STATS']], function () {
        Route::get('statistiques', 'StatistiquesController@index')->name('statistiques.index');
        Route::post('statistiqueSearch', 'StatistiquesController@statistiqueSearch')->name('statistiqueSearch');
        Route::get('getSessionsByInstance/{id_ins?}/{annee?}', 'RapportController@getSessionsByInstance')->name('getSessionsByInstance');
        Route::get('getActeursByInstance/{id_ins?}', 'RapportController@getActeursByInstance')->name('getActeursByInstance');
    });

    Route::resource('listeAlertes', 'ListeAlertesController');
    Route::resource('envoiAlertes', 'EnvoiAlertesController');

    Route::resource('programmeBudgetaires', 'ProgrammeBudgetairesController');
    Route::post('saveProgBug', 'ProgrammeBudgetairesController@saveProgBug')->name('saveProgBug');
    Route::get('getProgBug/{id_prog}', 'ProgrammeBudgetairesController@getProgBug')->name('getProgBug');
    Route::get('getAllProgBugs', 'ProgrammeBudgetairesController@getAllProgBugs')->name('getAllProgBugs');
    Route::get('deleteProgBug/{id_prog}', 'ProgrammeBudgetairesController@deleteProgBug')->name('deleteProgBug');
    Route::get('progBudgetaires/reload', 'ProgrammeBudgetairesController@reload')->name('progBudgetaires.reload');

app/Models/ListeAlertes.php
<?php

namespace App\Models;

use Eloquent as Model;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * Class ListeAlertes
 * @package App\Models
 * @version April 1, 2020, 10:25 am UTC
 *
 * @property \App\Models\Structure str
 * @property \App\Models\Session ses
 * @property \App\Models\User use
 * @property \Illuminate\Database\Eloquent\Collection alertes
 * @property integer ses_id
 * @property integer use_id
 * @property integer str_id
 * @property string lia_nom_prenom
 * @property string lia_email
 * @property string lia_sexe
 * @property string lia_fonction
 * @property string lia_matricule
 * @property string created_by
 * @property string updated_by
 */
class ListeAlertes extends Model
{

    use LogsActivity;

    public $table = 'liste_alertes';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';



    protected $primaryKey = 'lia_id';

    public $fillable = [
        'ses_id',
        'use_id',
        'str_id',
        'lia_nom_prenom',
        'lia_email',
        'lia_sexe',
        'lia_fonction',
        'lia_matricule',
        'created_by',
        'updated_by'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'lia_id' => 'integer',
        'ses_id' => 'integer',
        'use_id' => 'integer',
        'str_id' => 'integer',
        'lia_nom_prenom' => 'string',
        'lia_email' => 'string',
        'lia_sexe' => 'string',
        'lia_fonction' => 'string',
        'lia_matricule' => 'string',
        'created_by' => 'string',
        'updated_by' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'ses_id' => 'required',
        'use_id' => 'required',
        'str_id' => 'required',
        'lia_nom_prenom' => 'required',
        'lia_email' => 'required',
//        'lia_sexe' => 'required',
        'created_by' => 'required',
        'created_at' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function str()
    {
        return $this->belongsTo(\App\Models\Structure::class, 'str_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function ses()
    {
        return $this->belongsTo(\App\Models\Session::class, 'ses_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function age()
    {
        return $this->belongsTo(\App\Models\Agents::class, 'age_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function alertes()
    {
        return $this->belongsToMany(\App\Models\Alerte::class, 'envoialertes');
    }

    protected static $logName = 'Liste Alerte';
    public function getDescriptionForEvent(string $eventName): string
    {
        if ($eventName == 'created') {
            return "Création";
        } elseif ($eventName == 'updated') {
            return "Modification";
        } elseif ($eventName == 'deleted') {
            return "Suppression";
        }
    } 
}

app/Http/Controllers/ListeAlertesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateListeAlertesRequest;
use App\Http\Requests\UpdateListeAlertesRequest;
use App\Repositories\ListeAlertesRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class ListeAlertesController extends AppBaseController
{
    /** @var  ListeAlertesRepository */
    private $listeAlertesRepository;

    public function __construct(ListeAlertesRepository $listeAlertesRepo)
    {
        $this->listeAlertesRepository = $listeAlertesRepo;
    }

    /**
     * Display a listing of the ListeAlertes.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $listeAlertes = $this->listeAlertesRepository->all();

        return view('backend.liste_alertes.index')
            ->with('listeAlertes', $listeAlertes);
    }

    /**
     * Show the form for creating a new ListeAlertes.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.liste_alertes.create');
    }

    /**
     * Store a newly created ListeAlertes in storage.
     *
     * @param CreateListeAlertesRequest $request
     *
     * @return Response
     */
    public function store(CreateListeAlertesRequest $request)
    {
        $input = $request->all();

        $listeAlertes = $this->listeAlertesRepository->create($input);

        Flash::success('Liste Alertes saved successfully.');

        return redirect(route('listeAlertes.index'));
    }

    /**
     * Display the specified ListeAlertes.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $listeAlertes = $this->listeAlertesRepository->find($id);

        if (empty($listeAlertes)) {
            Flash::error('Liste Alertes not found');

            return redirect(route('listeAlertes.index'));
        }

        return view('backend.liste_alertes.show')->with('listeAlertes', $listeAlertes);
    }

    /**
     * Show the form for editing the specified ListeAlertes.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $listeAlertes = $this->listeAlertesRepository->find($id);

        if (empty($listeAlertes)) {
            Flash::error('Liste Alertes not found');

            return redirect(route('listeAlertes.index'));
        }

        return view('backend.liste_alertes.edit')->with('listeAlertes', $listeAlertes);
    }

    /**
     * Update the specified ListeAlertes in storage.
     *
     * @param int $id
     * @param UpdateListeAlertesRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateListeAlertesRequest $request)
    {
        $listeAlertes = $this->listeAlertesRepository->find($id);

        if (empty($listeAlertes)) {
            Flash::error('Liste Alertes not found');

            return redirect(route('listeAlertes.index'));
        }

        $listeAlertes = $this->listeAlertesRepository->update($request->all(), $id);

        Flash::success('Liste Alertes updated successfully.');

        return redirect(route('listeAlertes.index'));
    }

    /**
     * Remove the specified ListeAlertes from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $listeAlertes = $this->listeAlertesRepository->find($id);

        if (empty($listeAlertes)) {
            Flash::error('Liste Alertes not found');

            return redirect(route('listeAlertes.index'));
        }

        $this->listeAlertesRepository->delete($id);

        Flash::success('Liste Alertes deleted successfully.');

        return redirect(route('listeAlertes.index'));
    }
}

resources/views/backend/liste_alertes/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('listeAlertes.index') !!}">Liste Alertes</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Liste Alertes</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'listeAlertes.store']) !!}

                                   @include('backend.liste_alertes.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/backend/liste_alertes/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('listeAlertes.index') !!}">Liste Alertes</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Liste Alertes</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($listeAlertes, ['route' => ['listeAlertes.update', $listeAlertes->lia_id], 'method' => 'patch']) !!}

                              @include('backend.liste_alertes.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/backend/liste_alertes/fields.blade.php
<!-- Ses Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ses_id', 'Ses Id:') !!}
    {!! Form::number('ses_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Use Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('use_id', 'Use Id:') !!}
    {!! Form::number('use_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Str Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('str_id', 'Str Id:') !!}
    {!! Form::number('str_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Lia Nom Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lia_nom', 'Lia Nom:') !!}
    {!! Form::text('lia_nom', null, ['class' => 'form-control']) !!}
</div>

<!-- Lia Prenom Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lia_prenom', 'Lia Prenom:') !!}
    {!! Form::text('lia_prenom', null, ['class' => 'form-control']) !!}
</div>

<!-- Lia Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lia_email', 'Lia Email:') !!}
    {!! Form::text('lia_email', null, ['class' => 'form-control']) !!}
</div>

<!-- Lia Sexe Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lia_sexe', 'Lia Sexe:') !!}
    {!! Form::text('lia_sexe', null, ['class' => 'form-control']) !!}
</div>

<!-- Lia Fonction Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lia_fonction', 'Lia Fonction:') !!}
    {!! Form::text('lia_fonction', null, ['class' => 'form-control']) !!}
</div>

<!-- Lia Matricule Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lia_matricule', 'Lia Matricule:') !!}
    {!! Form::text('lia_matricule', null, ['class' => 'form-control']) !!}
</div>

<!-- Created By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('created_by', 'Created By:') !!}
    {!! Form::text('created_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Updated By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('updated_by', 'Updated By:') !!}
    {!! Form::text('updated_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('listeAlertes.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/backend/liste_alertes/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Liste Alertes</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             ListeAlertes
                             <a class="pull-right" href="{{ route('listeAlertes.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('backend.liste_alertes.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/backend/liste_alertes/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('listeAlertes.index') }}">Liste Alertes</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('listeAlertes.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('backend.liste_alertes.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/backend/liste_alertes/show_fields.blade.php
<!-- Ses Id Field -->
<div class="form-group">
    {!! Form::label('ses_id', 'Ses Id:') !!}
    <p>{{ $listeAlertes->ses_id }}</p>
</div>

<!-- Use Id Field -->
<div class="form-group">
    {!! Form::label('use_id', 'Use Id:') !!}
    <p>{{ $listeAlertes->use_id }}</p>
</div>

<!-- Str Id Field -->
<div class="form-group">
    {!! Form::label('str_id', 'Str Id:') !!}
    <p>{{ $listeAlertes->str_id }}</p>
</div>

<!-- Lia Nom Field -->
<div class="form-group">
    {!! Form::label('lia_nom', 'Lia Nom:') !!}
    <p>{{ $listeAlertes->lia_nom }}</p>
</div>

<!-- Lia Prenom Field -->
<div class="form-group">
    {!! Form::label('lia_prenom', 'Lia Prenom:') !!}
    <p>{{ $listeAlertes->lia_prenom }}</p>
</div>

<!-- Lia Email Field -->
<div class="form-group">
    {!! Form::label('lia_email', 'Lia Email:') !!}
    <p>{{ $listeAlertes->lia_email }}</p>
</div>

<!-- Lia Sexe Field -->
<div class="form-group">
    {!! Form::label('lia_sexe', 'Lia Sexe:') !!}
    <p>{{ $listeAlertes->lia_sexe }}</p>
</div>

<!-- Lia Fonction Field -->
<div class="form-group">
    {!! Form::label('lia_fonction', 'Lia Fonction:') !!}
    <p>{{ $listeAlertes->lia_fonction }}</p>
</div>

<!-- Lia Matricule Field -->
<div class="form-group">
    {!! Form::label('lia_matricule', 'Lia Matricule:') !!}
    <p>{{ $listeAlertes->lia_matricule }}</p>
</div>

<!-- Created By Field -->
<div class="form-group">
    {!! Form::label('created_by', 'Created By:') !!}
    <p>{{ $listeAlertes->created_by }}</p>
</div>

<!-- Updated By Field -->
<div class="form-group">
    {!! Form::label('updated_by', 'Updated By:') !!}
    <p>{{ $listeAlertes->updated_by }}</p>
</div>

resources/views/backend/liste_alertes/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="listeAlertes-table">
        <thead>
            <th>Ses Id</th>
        <th>Use Id</th>
        <th>Str Id</th>
        <th>Lia Nom</th>
        <th>Lia Prenom</th>
        <th>Lia Email</th>
        <th>Lia Sexe</th>
        <th>Lia Fonction</th>
        <th>Lia Matricule</th>
        <th>Created By</th>
        <th>Updated By</th>
            <th colspan="3">Action</th>
        </thead>
        <tbody>
        @foreach($listeAlertes as $listeAlertes)
            <tr>
                <td>{{ $listeAlertes->ses_id }}</td>
            <td>{{ $listeAlertes->use_id }}</td>
            <td>{{ $listeAlertes->str_id }}</td>
            <td>{{ $listeAlertes->lia_nom }}</td>
            <td>{{ $listeAlertes->lia_prenom }}</td>
            <td>{{ $listeAlertes->lia_email }}</td>
            <td>{{ $listeAlertes->lia_sexe }}</td>
            <td>{{ $listeAlertes->lia_fonction }}</td>
            <td>{{ $listeAlertes->lia_matricule }}</td>
            <td>{{ $listeAlertes->created_by }}</td>
            <td>{{ $listeAlertes->updated_by }}</td>
                <td>
                    {!! Form::open(['route' => ['listeAlertes.destroy', $listeAlertes->lia_id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('listeAlertes.show', [$listeAlertes->lia_id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('listeAlertes.edit', [$listeAlertes->lia_id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>